name: test_workflow

on:
  push:
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: create a Folder
        run: mkdir new_folder

      - name: list folders
        run: ls -l
